services:
  db:
    image: postgres:18-alpine
    container_name: proyecto-pruebas-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./apps/api/bd:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

    container_name: proyecto-pruebas-api

    environment:
      NODE_ENV: development
      PORT: 3000

      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      CORS_ORIGIN: http://localhost:5173

    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile

    container_name: proyecto-pruebas-web

    environment:
      VITE_API_URL: http://localhost:3000/api

    ports:
      - "5173:5173"

    depends_on:
      - api

volumes:
  postgres_data:
